# ARG version
FROM almalinux:10
# RUN cat /etc/*release 
ARG course=docker
ARG Tranier=shivakumar 
ARG Duration=120hrs
ENV Duration=${Duration}
RUN echo "Trainer is: ${Tranier}","course is: ${course}","Duration:${Duration}"
CMD [ "sleep","100" ]

 