ARG version
FROM almalinux:${version}
RUN cat /etc/*release 
# ARG course
# ARG Tranier
# ENV Duration=129
# RUN echo "Trainer is: ${Tranier}","course is: ${course}","Duration:${Duration}"
# CMD [ "sleep","100" ]

 